### PR TITLE
Issue #11: Changed the URI type from akka.http.scaladsl.model.Uri to …

### PR DESCRIPTION
**Pull request by Deeds67**
Changed the URI type from akka.http.scaladsl.model.Uri to java.net.URI.

Signed-off-by: Pierre Marais <pierre.david.marais@zalando.de>

### CODE REVIEW

**Comment by xjrk58** [comment]
@Deeds67 Could you sign off your commit with correct email address?

**Comment by mdedetrich** [comment]
@Deeds67 @xjrk58 I think the email is correct (at least reading from the commit), maybe it only works with zalando emails?

**Comment by Deeds67** [comment]
@mdedetrich Added the functional test.

**Comment by mdedetrich** [comment]
@Deeds67 Sorry for being pedantic, but can you put `createEnoughSubscriptionsToUsePagination` into its own file (i.e. `SubscriptionsSpec` or something like that).

The reason is that `BasicSpec` is meant to be testing the basic flow of creating a subscription and sending events, i.e. its an integration test.

**Comment by Deeds67** [comment]
@mdedetrich 
No problem, implemented the change.

**Pull request merged**
